// Execution Agent - Performs concrete actions (Mock implementation for MVP)

import { BaseAgent } from './base-agent';
import type { AgentInput, AgentOutput, AgentType } from '@/types/workflow';

export class ExecutionAgent extends BaseAgent {
  type: AgentType = 'execution';

  async execute(input: AgentInput): Promise<AgentOutput> {
    await this.updateStepStatus(input.step_id, 'running');
    await this.logMessage(input.workflow_id, input.step_id, 'started', {
      message: 'Starting execution phase',
      task: input.context.task || 'Execute planned action',
    });

    try {
      // Simulate execution delay (2-4 seconds for more complex work)
      await new Promise(resolve => setTimeout(resolve, 2000 + Math.random() * 2000));

      // Get research findings from memory if available
      const findings = await this.getMemory(input.workflow_id, 'research_findings');
      
      // Generate mock output based on the step description and findings
      const result = this.generateExecutionResult(input.goal, input.context, findings);

      await this.logMessage(input.workflow_id, input.step_id, 'executed', {
        message: 'Execution completed successfully',
        result_type: result.type,
      });

      // Store result in memory
      await this.setMemory(input.workflow_id, `execution_result_${input.step_id}`, result);

      await this.updateStepStatus(input.step_id, 'completed', { result });

      return {
        success: true,
        data: { result },
        message: `Execution complete: ${result.type}`,
      };
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Execution failed';
      
      await this.logMessage(input.workflow_id, input.step_id, 'error', { error: errorMessage });
      await this.updateStepStatus(input.step_id, 'failed', undefined, errorMessage);

      return {
        success: false,
        data: {},
        message: 'Execution phase failed',
        error: errorMessage,
      };
    }
  }

  private generateExecutionResult(
    goal: string,
    context: Record<string, unknown>,
    findings: Record<string, unknown> | null
  ): {
    type: string;
    content: string;
    metadata: Record<string, unknown>;
  } {
    const goalLower = goal.toLowerCase();
    const stepName = (context.step_name as string) || '';
    const stepNameLower = stepName.toLowerCase();

    // Determine output type based on step or goal
    if (stepNameLower.includes('report') || stepNameLower.includes('summary') || goalLower.includes('report')) {
      return {
        type: 'report',
        content: this.generateReport(goal, findings),
        metadata: {
          format: 'markdown',
          word_count: 450,
          sections: ['Executive Summary', 'Key Findings', 'Analysis', 'Recommendations'],
        },
      };
    }

    if (stepNameLower.includes('analyze') || stepNameLower.includes('analysis')) {
      return {
        type: 'analysis',
        content: this.generateAnalysis(goal, findings),
        metadata: {
          confidence: 0.87,
          data_sources: findings ? 3 : 1,
        },
      };
    }

    if (stepNameLower.includes('content') || stepNameLower.includes('write') || goalLower.includes('marketing')) {
      return {
        type: 'content',
        content: this.generateContent(goal),
        metadata: {
          format: 'text',
          target_audience: 'general',
        },
      };
    }

    // Default generic execution result
    return {
      type: 'task_completion',
      content: `Task "${stepName || 'action'}" completed successfully based on the goal: "${goal}"`,
      metadata: {
        status: 'completed',
        timestamp: new Date().toISOString(),
      },
    };
  }

  private generateReport(goal: string, findings: Record<string, unknown> | null): string {
    const keyFacts = (findings?.key_facts as string[]) || ['Analysis completed successfully'];
    
    return `# Executive Summary

This report analyzes the key aspects related to: "${goal}"

## Key Findings

${keyFacts.map((fact, i) => `${i + 1}. ${fact}`).join('\n')}

## Analysis

Based on comprehensive research and data analysis, we have identified several important insights that are relevant to the stated objective. The findings indicate positive trends and opportunities for strategic action.

## Recommendations

1. Proceed with the identified opportunities
2. Monitor key metrics for continued performance
3. Consider additional analysis for deeper insights

---
*Report generated by Execution Agent*`;
  }

  private generateAnalysis(goal: string, findings: Record<string, unknown> | null): string {
    const dataPoints = (findings?.data_points as Record<string, unknown>[]) || [];
    
    return `Analysis Results for: "${goal}"

Confidence Score: 87%
Data Sources Analyzed: ${dataPoints.length || 2}

Summary:
The analysis reveals consistent patterns that support the stated objectives. Key metrics show positive trends with room for optimization in specific areas.

${dataPoints.length > 0 ? `\nData Points:\n${dataPoints.map(dp => `- ${dp.metric}: ${dp.value}`).join('\n')}` : ''}`;
  }

  private generateContent(goal: string): string {
    return `Generated Content for: "${goal}"

[Content Preview]
This is professionally crafted content designed to meet the specified objectives. It incorporates best practices and is optimized for the target audience.

The content follows a clear structure with:
- Engaging introduction
- Value proposition
- Call to action

This content is ready for review and can be customized further based on specific requirements.`;
  }
}
